//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nakliyat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class defaultHizmetSayfasiBilgileri
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
        public string resim { get; set; }
        public string keywords { get; set; }
        public string siteAciklamasi { get; set; }
        public string siteFullKodu { get; set; }
    }
}
