//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nakliyat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pageIletisim
    {
        public int id { get; set; }
        public string solBaslik1 { get; set; }
        public string solİcerik1 { get; set; }
        public string haritaLinki { get; set; }
    }
}
