//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nakliyat.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class pagesHizmetEkleme
    {
        public int id { get; set; }
        public string fotograf1 { get; set; }
        public string fotograf2 { get; set; }
        public string fotograf3 { get; set; }
        [AllowHtml]
        public string icerik { get; set; }
        public string sayfaAciklamasi { get; set; }
        public string keywords { get; set; }
        public string sayfaAdıIngilizceHarfli { get; set; }
        public string goruntulenecekAd { get; set; }
    }
}
