//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nakliyat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pageHakkimizdaa
    {
        public int id { get; set; }
        public string baslik1 { get; set; }
        public string icerik1 { get; set; }
        public string baslik2 { get; set; }
        public string icerik2 { get; set; }
        public string icerik2ArkaplanResmi { get; set; }
    }
}
