//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nakliyat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sirketBilgileri
    {
        public int id { get; set; }
        public string isim { get; set; }
        public string adres { get; set; }
        public string telefon1 { get; set; }
        public string telefon2 { get; set; }
        public string mail { get; set; }
        public string facebook { get; set; }
        public string linkedin { get; set; }
        public string twitter { get; set; }
        public string siteAciklamasi { get; set; }
        public string siteKeywordleri { get; set; }
        public int serverDakikaTamamlama { get; set; }
        public string URL_Sitemap_icin { get; set; }
    }
}
